[package]
name = "zehn"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1"
authors = ["Marvin Friedrich <contact@marvinf.com>"]
repository = "https://github.com/marv7000/zehn/"

[dependencies]
indexmap = "2.2.5"
